# Generated by Django 2.1.5 on 2021-07-30 11:53

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_group', models.BooleanField(default=False)),
                ('avi', models.ImageField(default='/defaults/artist.png', upload_to=music.models.upload_artist_image)),
                ('cover', models.ImageField(default='/defaults/artist_large.png', upload_to=music.models.upload_artist_image)),
                ('bio', models.TextField(blank=True, null=True)),
                ('nicknames', models.TextField(blank=True, help_text='Comma separated names the artist goes by', null=True)),
                ('group_members', models.ManyToManyField(blank=True, null=True, related_name='_artist_group_members_+', to='music.Artist')),
            ],
        ),
    ]
