# Generated by Django 2.1.5 on 2021-07-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='group_members',
            field=models.ManyToManyField(related_name='_artist_group_members_+', to='music.Artist'),
        ),
    ]
