# Generated by Django 2.1.5 on 2021-07-30 12:22

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210730_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('avi', models.ImageField(default='/defaults/creator.png', upload_to=music.models.upload_creator_image)),
                ('cover', models.ImageField(default='/defaults/creator_wide.png', upload_to=music.models.upload_creator_image)),
            ],
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
