# Generated by Django 2.1.5 on 2021-08-03 11:23

from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_of_release', models.DateField()),
                ('is_single', models.BooleanField(default=False)),
                ('is_ep', models.BooleanField(default=False)),
                ('cover', models.ImageField(default='/defaults/genre.png', upload_to=music.models.upload_album_image)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('copyright', models.TextField(blank=True, null=True)),
                ('artists', models.ManyToManyField(to='music.Artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Genre')),
                ('other_versions', models.ManyToManyField(related_name='_album_other_versions_+', to='music.Album')),
            ],
        ),
    ]
