# Generated by Django 2.1.5 on 2021-08-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(blank=True, null=True, to='music.Artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='other_versions',
            field=models.ManyToManyField(blank=True, null=True, related_name='_album_other_versions_+', to='music.Album'),
        ),
    ]
