# Generated by Django 2.1.5 on 2021-08-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20210803_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
