# Generated by Django 2.1.5 on 2021-08-03 12:56

from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_album_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_no', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('explicit', models.BooleanField(default=False)),
                ('length', models.CharField(default='00:00', max_length=8)),
                ('file', models.FileField(blank=True, null=True, upload_to=music.models.upload_song_file)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('streams', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.Genre'),
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album'),
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(to='music.Artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.Genre'),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('album', 'track_no')},
        ),
    ]
