# Generated by Django 2.1.5 on 2021-08-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20210803_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artists',
            new_name='additional_artists',
        ),
    ]
