# Generated by Django 2.1.5 on 2021-08-03 14:39

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20210803_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='/defaults/album.png', upload_to=music.models.upload_album_image),
        ),
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.IntegerField(default=0, help_text='Length of the song in seconds'),
        ),
    ]
