# Generated by Django 2.1.5 on 2021-08-03 15:49

from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210727_1602'),
        ('music', '0014_auto_20210803_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('songs_order', models.TextField(blank=True, default='', help_text='Comma separated digits indicating a pk for each song', null=True)),
                ('likes', models.IntegerField(default=0)),
                ('cover', models.ImageField(default='/defaults/playlist.png', upload_to=music.models.upload_playlist_image)),
                ('cover_wide', models.ImageField(default='/defaults/playlist_wide.png', upload_to=music.models.upload_playlist_image)),
                ('timely_cover', models.ImageField(blank=True, null=True, upload_to=music.models.upload_playlist_image)),
                ('timely_cover_wide', models.ImageField(blank=True, null=True, upload_to=music.models.upload_playlist_image)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Creator')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
                ('songs', models.ManyToManyField(blank=True, to='music.Song')),
            ],
        ),
    ]
