# Generated by Django 2.1.5 on 2021-08-03 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('albums', models.ManyToManyField(blank=True, to='music.Album')),
                ('artists', models.ManyToManyField(blank=True, to='music.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='creator',
            name='genres',
            field=models.ManyToManyField(blank=True, to='music.Genre'),
        ),
        migrations.AddField(
            model_name='creatorsection',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Creator'),
        ),
        migrations.AddField(
            model_name='creatorsection',
            name='playlists',
            field=models.ManyToManyField(blank=True, to='music.Playlist'),
        ),
    ]
