# Generated by Django 2.1.5 on 2021-08-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_auto_20210804_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
