# Generated by Django 2.1.5 on 2021-08-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_remove_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='group_members',
            field=models.ManyToManyField(blank=True, related_name='_artist_group_members_+', to='music.Artist'),
        ),
    ]
