# Generated by Django 2.1.5 on 2021-08-05 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_auto_20210805_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='disc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Disc'),
        ),
    ]
