# Generated by Django 2.1.5 on 2021-08-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_auto_20210805_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
