# Generated by Django 2.1.5 on 2021-08-10 12:46

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_playlist_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='playlists',
            field=models.ManyToManyField(to='music.Playlist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='avi',
            field=models.ImageField(default='/defaults/artist.png', help_text='A 1x1 pic', upload_to=music.models.upload_artist_image),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, help_text='Info about the artist', null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='cover',
            field=models.ImageField(default='/defaults/artist_large.png', help_text='16x16', upload_to=music.models.upload_artist_image),
        ),
        migrations.AlterField(
            model_name='artist',
            name='is_group',
            field=models.BooleanField(default=False, help_text='Is the artist a group'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(help_text="Artist's name", max_length=100),
        ),
    ]
