# Generated by Django 2.1.5 on 2021-08-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0027_auto_20210810_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='playlists',
            field=models.ManyToManyField(blank=True, to='music.Playlist'),
        ),
    ]
