# Generated by Django 2.1.5 on 2021-08-10 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0028_auto_20210810_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='main_curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='music.Creator'),
        ),
    ]
