# Generated by Django 2.1.5 on 2021-08-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0029_genre_main_curator'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='featured_artists',
            field=models.ManyToManyField(blank=True, related_name='features', to='music.Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='additional_artists',
            field=models.ManyToManyField(blank=True, related_name='song_artists', to='music.Artist'),
        ),
    ]
