# Generated by Django 2.1.5 on 2021-08-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0030_auto_20210810_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='additional_artists',
            field=models.ManyToManyField(blank=True, related_name='additions', to='music.Artist'),
        ),
    ]
