# Generated by Django 2.1.5 on 2021-07-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('S', 'SINGLE'), ('F', 'FAMILY')], default='S', max_length=2),
        ),
    ]
