# Generated by Django 2.1.5 on 2021-07-25 19:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210725_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avi',
            field=models.ImageField(default='/accounts/avis/default.jpg', upload_to=core.models.upload_avi),
        ),
    ]
