# Generated by Django 2.1.5 on 2021-07-25 23:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_profile_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avi',
            field=models.ImageField(default='/accounts/avis/defaults/default.jpg', upload_to=core.models.upload_avi),
        ),
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('S', 'Single'), ('F', 'Family')], default='S', max_length=2),
        ),
    ]
