# Generated by Django 2.1.5 on 2021-07-25 23:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210726_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avi',
            field=models.ImageField(default='/defaults/default_profile.jpg', upload_to=core.models.upload_avi),
        ),
    ]
