# Generated by Django 2.1.5 on 2021-08-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helparticle',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
